<?php
$product = Mage::registry('current_product');
$prod_data = array(
    'id' => $product->getSku(),
    'name' => $product->getName(),
    'price' => round($product->getFinalPrice(), 2),
);
if (Mage::registry('current_category')) {
    // TODO CATEGORY BREADCRUMBS
    // "category": "Одежда/Мужская одежда/Футболки",
    $prod_data['category'] = Mage::registry('current_category')->getName();
}
// TODO
//'brand' => '',
//'variant' => '',
$data = array(
    'ecommerce' => array(
        'detail' => array(
            'products' => array(
                $prod_data
            )
        )
    )
);

?>
<script>
    dataLayer.push(<?php echo Mage::helper('core')->jsonEncode($data); ?>);
</script>
