<?php
$lastid = Mage::getSingleton('checkout/type_onepage')->getCheckout()->getLastOrderId();
$order = Mage::getSingleton('sales/order')->load($lastid);
foreach ($order->getAllVisibleItems() as $item) {
    $prod_data[] = array(
        'id' => $item->getSku(),
        'name' => $item->getName(),
        'price' => $item->getPrice(),
        'quantity' => (int) $item->getQtyOrdered()
    );
}
$data = array(
    'ecommerce' => array(
        'purchase' => array(
            'actionField' => array(
                'id' => (string) $order->getIncrementId(),
                'shipping' => $order->getShippingAmount(),
            ),
            'products' => $prod_data,
        )
    )
);

?>
<script>
    dataLayer.push(<?php echo Mage::helper('core')->jsonEncode($data); ?>);
</script>
